export interface SalaryVariant {
  slug: string;
  ctc: number;
  label: string;
  state: string;
  city: "metro" | "non-metro";
  description: string;
}

export const salaryVariants: SalaryVariant[] = [
  {
    slug: "5-lpa",
    ctc: 500000,
    label: "5 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹5 LPA CTC in India 2025.",
  },
  {
    slug: "8-lpa",
    ctc: 800000,
    label: "8 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹8 LPA CTC in India 2025.",
  },
  {
    slug: "10-lpa",
    ctc: 1000000,
    label: "10 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹10 LPA CTC in India 2025.",
  },
  {
    slug: "12-lpa",
    ctc: 1200000,
    label: "12 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹12 LPA CTC in India 2025.",
  },
  {
    slug: "15-lpa",
    ctc: 1500000,
    label: "15 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹15 LPA CTC in India 2025.",
  },
  {
    slug: "18-lpa",
    ctc: 1800000,
    label: "18 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹18 LPA CTC in India 2025.",
  },
  {
    slug: "20-lpa",
    ctc: 2000000,
    label: "20 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹20 LPA CTC in India 2025.",
  },
  {
    slug: "25-lpa",
    ctc: 2500000,
    label: "25 LPA",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary for ₹25 LPA CTC in India 2025.",
  },
  {
    slug: "30-lpa",
    ctc: 3000000,
    label: "30 LPA",
    state: "Maharashtra",
    city: "metro",
    description: "In-hand salary for ₹30 LPA CTC in India 2025.",
  },
  {
    slug: "35-lpa",
    ctc: 3500000,
    label: "35 LPA",
    state: "Maharashtra",
    city: "metro",
    description: "In-hand salary for ₹35 LPA CTC in India 2025.",
  },
  {
    slug: "40-lpa",
    ctc: 4000000,
    label: "40 LPA",
    state: "Maharashtra",
    city: "metro",
    description: "In-hand salary for ₹40 LPA CTC in India 2025.",
  },
  {
    slug: "50-lpa",
    ctc: 5000000,
    label: "50 LPA",
    state: "Maharashtra",
    city: "metro",
    description: "In-hand salary for ₹50 LPA CTC in India 2025.",
  },
  {
    slug: "bangalore",
    ctc: 1200000,
    label: "Bangalore",
    state: "Karnataka",
    city: "metro",
    description: "In-hand salary calculator for Bangalore (Karnataka) employees.",
  },
  {
    slug: "mumbai",
    ctc: 1500000,
    label: "Mumbai",
    state: "Maharashtra",
    city: "metro",
    description: "In-hand salary calculator for Mumbai (Maharashtra) employees.",
  },
  {
    slug: "hyderabad",
    ctc: 1200000,
    label: "Hyderabad",
    state: "Telangana",
    city: "metro",
    description: "In-hand salary calculator for Hyderabad (Telangana) employees.",
  },
  {
    slug: "chennai",
    ctc: 1000000,
    label: "Chennai",
    state: "Tamil Nadu",
    city: "metro",
    description: "In-hand salary calculator for Chennai (Tamil Nadu) employees.",
  },
  {
    slug: "pune",
    ctc: 1000000,
    label: "Pune",
    state: "Maharashtra",
    city: "non-metro",
    description: "In-hand salary calculator for Pune (Maharashtra) employees.",
  },
  {
    slug: "kolkata",
    ctc: 800000,
    label: "Kolkata",
    state: "West Bengal",
    city: "metro",
    description: "In-hand salary calculator for Kolkata (West Bengal) employees.",
  },
  {
    slug: "delhi",
    ctc: 1200000,
    label: "Delhi",
    state: "Delhi",
    city: "metro",
    description: "In-hand salary calculator for Delhi employees.",
  },
  {
    slug: "ahmedabad",
    ctc: 800000,
    label: "Ahmedabad",
    state: "Gujarat",
    city: "non-metro",
    description: "In-hand salary calculator for Ahmedabad (Gujarat) employees.",
  },
];
